# permissions for end users to edit resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-tf-controller
    app.kubernetes.io/managed-by: kustomize
  name: resource-editor-role
rules:
- apiGroups:
  - terragrunt.yaakov.com
  resources:
  - resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - terragrunt.yaakov.com
  resources:
  - resources/status
  verbs:
  - get
