apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfcontroller
  labels:
    app: tfcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tfcontroller
  template:
    metadata:
      labels:
        app: tfcontroller
    spec:
      serviceAccountName: tf-controller
      containers:
      - name: tfcontroller
        image: tfcontroller-test
        ports:
        - containerPort: 80
