apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfbackends.terraform.iac.operator
spec:
  group: terraform.iac.operator
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                path:
                  type: string
                type:
                  type: string
  scope: Namespaced
  names:
    plural: tfbackends
    singular: tfbackend
    kind: TfBackend
    shortNames:
    - tfb