apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfprojects.terraform.iac.operator
spec:
  group: terraform.iac.operator
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                path:
                  type: string
                repository:
                  type: string
                backend:
                  type: string
                interval:
                  type: integer
                variables:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: tfprojects
    singular: tfproject
    kind: TfProject
    shortNames:
    - tfp