apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tfrepos.terraform.iac.operator
spec:
  group: terraform.iac.operator
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
  scope: Namespaced
  names:
    plural: tfrepos
    singular: tfrepo
    kind: TfRepo
    shortNames:
    - tfr